### ISSUE TITLE
Server CORS Configuration change

### ISSUE THREAD

**Issue by Seitus** [Comp231TeamBourque/Umbraco-CMS#18]
http://enable-cors.org/server_apache.html

**Comment by tylerbourque** [comment]
I got ssh access to the server on open shift and there is now access to the Apache configuration file on the server at all. so the headers in the response can not be changed.

**Comment by kanadon** [comment]
did you mean "there is NO access"?

**Comment by tylerbourque** [comment]
there was no configuration folder, i did find what i believe to be the Apache configuration and it seems to be working now. if you visit this link you should be able to see json. http://sbawebdev-dataparser.rhcloud.com/api/get_recent_posts/

**Comment by Seitus** [comment]
Managed to resolve the issue after adding a php header to the JSON API Plugin. Reference: http://stackoverflow.com/questions/25702061/enable-cors-on-json-api-wordpress, it still did not work after the change to the server, but it works fine now.

**Comment by kanadon** [comment]
I got the posts to show up on my android

http://www.filedropper.com/android-debug

**Comment by tylerbourque** [comment]
Looks awesome very clean actually. I thought ui wize it was going to looks bad but I am actually very impressed. Have you pushed your changes to the repo yet? Also if you we collectively decided that we want to publish the app even in alpha, I have a developer account we could possibly publish it. I think it needs further discussion. We should meet sometime this week to discuss further steps.

**Comment by kanadon** [comment]
Which repo should I use? App or Compile?

I'm busy tomorrow night, but we should definitely meet this week.

**Comment by tylerbourque** [comment]
Whichever one fits the layout that you have I think the compile repo is the layout that you have. Just check to see. The app repo has a sub-folder that contains all the Cordova files

**Comment by kanadon** [comment]
Done.

I'm actually experiencing a little issue on my android. With each transition, the page scrolls up and down 1px, as described here (https://github.com/jquery/jquery-mobile/issues/5488). Very annoying. Could somebody test it on their phone?

**Comment by tylerbourque** [comment]
awesome. I was able to replicate this issue on my phone didn't notice it until just now when i was looking for it. i will read the issue on jquery mobile and see if there is a good solution.

**Comment by kanadon** [comment]
Issue is resolved by using hanspeerstra's solution

https://github.com/jquery/jquery-mobile/issues/5488#issuecomment-108613536
